FROM jenkins/jenkins:lts
USER root
RUN apt update && apt install -y docker.io  curl &&  curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose &&  chmod +x /usr/local/bin/docker-compose && usermod -aG docker jenkins
USER jenkins