version: "3.8"
services:
  web:
    image: amira/flask-app:latest
    ports:
      - "5008:5000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "taxdb"
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "0:3306"
  grafana:
    image: grafana/grafana
    ports:
      - "0:3000"  
    volumes:
      - grafana-data:/var/lib/grafana  
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus:/etc/prometheus"
    ports:
      - "0:9090"
volumes:
  db-data:
  grafana-data:
      
